### ISSUE TITLE
RedBull Iframe test url no longer working

### ISSUE THREAD

**Issue by headjump** [redbullmediahouse/rbcom-responsive-iframe-example#1]
Hi, we are working on integrating an APP into your IFrame, but the testing URLs for local testing are no longer available. Neither the URL you use here nor the URL from the Custom-Components documentation. Could you please check?

Thanks :)

**Comment by ALibrada** [comment]
It works for me. Did you check the documentation? You have to allow the exception for a self signed certificate and load the iframe using https

**Comment by headjump** [comment]
Issue can be closed. It worked for me before also (I already set is up some time ago), but strangely I got a 404 on RedBulls side for the URL last week (not inside the embedded frame but on the site itself). This week I can reach it again. Thanks for your quick response.
