### ISSUE TITLE
Message to scroll to beginning of IFrame after changing page inside it?

### ISSUE THREAD

**Issue by headjump** [redbullmediahouse/rbcom-responsive-iframe-example#2]
Hi,

we use a predefined Message to update the dimension of the IFrame on height-change, which is working just fine:

```
canvas.source.postMessage("RedBullCanvas:setHeight:" + uri + ":" + height, "*");
```

Is there an equivalent message to ask the containing page to scroll to the beginning of the IFrame? Can you point me to a documentation of the API for the supported messages?

If users click links inside the IFrame the scroll position of the containing page is of course not changed. So the user is somewhere in the middle of the next IFrame-page after clicking a link inside it.

**Comment by ALibrada** [comment]
We don’t have that kind of API. You can create a custom script that listens to the message and there you can implement that feature.
In my opinion you should use custom scripts for everything instead of iframes so you don’t need those ugly workarounds.

**Comment by headjump** [comment]
OK, thanks.
